title = "szacilowski.com"
baseurl = "http://www.example.com"
languagecode = "en"
defaultcontentlanguage = "en"
theme = "hugo-coder"
paginate = 20
canonifyurls = true
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
disqusShortname = "yourdiscussshortname"

[params]
author = "Piotr Szaciłowski"
description = "Piotr Szaciłowski personal website"
keywords = "blog,developer,personal"
info = "Student of computer science, aspiring software developer."

avatarurl = "images/avatar.jpg"
hideFooter = false
#footercontent = "Enter a text here."
dateformat = "January 2, 2006"
hideCredits = false
hideCopyright = false
since = 2020

commit = "https://github.com/luizdepra/hugo-coder/tree/"
rtl = false

colorscheme = "auto"
maxSeeAlsoItems = 5

custom_css = [ ]

custom_js = [ ]

  [[params.social]]
  name = "Github"
  icon = "fab fa-github"
  weight = 1
  url = "https://github.com/piotrszacilowski/"

  [[params.social]]
  name = "Twitter"
  icon = "fab fa-twitter"
  weight = 2
  url = "https://twitter.com/szacilowski/"

  [[params.social]]
  name = "LinkedIn"
  icon = "fab fa-linkedin"
  weight = 4
  url = "https://www.linkedin.com/in/piotrszacilowski/"

  [[params.social]]
  name = "RSS"
  icon = "fas fa-rss"
  weight = 6
  url = "https://myhugosite.com/index.xml"
  rel = "alternate"
  type = "application/rss+xml"

  [params.fathomAnalytics]
  siteID = "ABCDE"
  serverURL = "analytics.example.com"

[languages.en]
languagename = "English"

[[languages.en.menu.main]]
name = "About"
url = "about/"
weight = 1

[[languages.en.menu.main]]
name = "Blog"
url = "posts/"
weight = 2

[[languages.en.menu.main]]
name = "Projects"
url = "projects/"
weight = 3

[[languages.en.menu.main]]
name = "Contact me"
url = "contact/"
weight = 5